# Generated by Django 2.2.6 on 2019-10-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20191006_0127'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test',
            field=models.ManyToManyField(related_name='test', to='tests.Test'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='static/img/users'),
        ),
    ]
