# Generated by Django 2.2.6 on 2019-10-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191006_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/img/user-default.png', null=True, upload_to='static/img/users'),
        ),
    ]
