# Generated by Django 2.2.6 on 2019-10-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
        ('home', '0002_auto_20191006_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test',
        ),
        migrations.AddField(
            model_name='profile',
            name='tests',
            field=models.ManyToManyField(related_name='user', to='tests.Test'),
        ),
    ]
