# Generated by Django 2.2.6 on 2019-10-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191006_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tests',
        ),
    ]
