# Generated by Django 2.2.6 on 2019-10-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191006_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/static/img/user-default.png', null=True, upload_to='static/img/users'),
        ),
    ]
