# Generated by Django 2.2.6 on 2019-10-04 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_edit',
        ),
    ]
