# Generated by Django 2.2.6 on 2019-10-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_usertestpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestpass',
            name='amount_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertestpass',
            name='correct_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertestpass',
            name='correct_present',
            field=models.IntegerField(default=0),
        ),
    ]
