# Generated by Django 2.2.6 on 2019-10-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_comment_is_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
